name: .NET Social ToolbarApp

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    name: Build and Release Toolbar
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Use 8.0.x se estiver com .NET 8

    - name: Restore dependencies
      run: dotnet restore ToolbarApp.csproj --runtime win-x64

    - name: Build application
      run: dotnet build ToolbarApp.csproj --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish ToolbarApp.csproj --configuration Release --runtime win-x64 --self-contained true --output ./app-publish
!!

    - name: Zip Release Artifact
      run: Compress-Archive -Path ./app-publish/* -DestinationPath ToolbarApp-${{ github.ref_name }}.zip
      shell: pwsh


    - name: Install Inno Setup
      run: choco install innosetup --yes

    - name: Compile installer with Inno Setup
      run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer.iss /dAppVersion=${{ github.ref_name }}'

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ToolbarApp ${{ github.ref_name }}
        body: |
          Release Social Media Toolbar
        draft: false
        prerelease: false

    - name: Upload Release Artifact (.zip)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ToolbarApp-${{ github.ref_name }}.zip
        asset_name: ToolbarApp-${{ github.ref_name }}.zip
        asset_content_type: application/zip

    - name: Upload Installer (.exe)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ToolbarInstaller.exe
        asset_name: ToolbarInstaller-${{ github.ref_name }}.exe
        asset_content_type: application/vnd.microsoft.portable-executable
